#
# Copyright zhigui Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  byfn:

services:
  orderer-seek:
    container_name: fabric-orderer-seek
    image: hyperledger/fabric-orderer-seek
    ports:
      - 8080:8080
    volumes:
      - ./conf:/go/src/fabric-orderer-seek/conf
      - ./sampleconfig:/go/src/fabric-orderer-seek/sampleconfig
      - /tmp/orderer-seek-logs:/go/src/fabric-orderer-seek/logs
    networks:
      - byfn