---

application:
  logPath: logs
  logLevel: 7
  local: true
  clients: 1
  cpus: 1
  orderers:
    - name: orderer
      host: orderer.example.com
      port: 7050
  ordererMsp: OrdererMSP
  profile: TwoOrgsOrdererGenesis #departed
  channels:
    - mychannel
  tlsEnabled: true
  reqTimeout: 120
  db:
    user: root
    password: zhigui
    name: explore
  txNumPerBlock: 100
  seekPositon: 1 # 0 oldest 1 newest

